### PR TITLE
fix(validate_rules): support sqlglot >=23 – use find() for FROM clause and fix Expression import

### LINKED ISSUE #8: fix(validate_rules): sqlglot >=23.0 compatibility – use find() instead of args.get('from')
## Problem

The `_validate_single_subquery` method in `spark_expectations/utils/validate_rules.py` uses `inner.args.get("from")` to locate the FROM clause of a parsed SQL subquery. This approach relies on an internal sqlglot dictionary key that was **renamed from `"from"` to `"from_"` in sqlglot v23.0**.

As a result, the constraint in `pyproject.toml` is currently pinned to `sqlglot>=21.0,<23.0` to avoid a silent breakage: with sqlglot ≥ 23 the method always returns `None` for the FROM node and incorrectly raises `SparkExpectationsInvalidRowDQExpectationException` for every valid row-DQ subquery expression like:

```python
col1 IN (SELECT id FROM ref_table)
```

## Root Cause

In sqlglot v22 the internal `Select` node stores the FROM clause under the key `"from"`:
```python
# sqlglot 22.x
inner.args.get("from")  # → From(...)
```

Starting with sqlglot v23 the key was renamed to `"from_"` (with trailing underscore):
```python
# sqlglot 23+
inner.args.get("from")  # → None  ← silent bug
inner.args.get("from_") # → From(...)
```

## Proposed Fix

Replace the fragile `args.get()` lookup with the public `find()` traversal API, which is stable across all sqlglot versions:

```python
# Before (breaks on sqlglot ≥ 23)
from_node = inner.args.get("from")
if not isinstance(from_node, sqlglot.expressions.From):
    raise SparkExpectationsInvalidRowDQExpectationException(...)

# After (works on sqlglot 21–30+)
from_node = inner.find(sqlglot.expressions.From)
if from_node is None:
    raise SparkExpectationsInvalidRowDQExpectationException(...)
```

After this one-line fix, the `sqlglot` upper bound in `pyproject.toml` can safely be raised from `<23.0` to `<31.0`, giving users access to 2+ years of sqlglot improvements.

## Verification

Manually tested with sqlglot 22.5.0 and 30.2.1 – `find(expressions.From)` returns the correct `From` node in both versions.

## Files Changed

- `spark_expectations/utils/validate_rules.py` — replace `args.get("from")` with `find(expressions.From)`
- `pyproject.toml` — bump sqlglot upper bound from `<23.0` to `<31.0`

### PR DESCRIPTION
**Pull request by asingamaneni**
## Summary

Fixes two sqlglot API incompatibilities that prevented spark-expectations from working with sqlglot >= 23.0, and bumps the allowed version range accordingly.

### Problem

The `pyproject.toml` constraint `sqlglot>=21.0,<23.0` was intentionally restrictive because of two breaking changes introduced in sqlglot v23:

**1. `sqlglot.Expression` removed from top-level module**

In sqlglot ≥ 23, `sqlglot.Expression` raises `AttributeError`. The class is only accessible as `sqlglot.expressions.Expression`. The module failed to import entirely with newer sqlglot:

```
AttributeError: module 'sqlglot' has no attribute 'Expression'. Did you mean: 'expressions'?
```

**2. `Select.args["from"]` key renamed to `"from_"`**

In `_validate_single_subquery`, `inner.args.get("from")` was used to locate the FROM clause. In sqlglot ≥ 23 the internal key was renamed to `"from_"`, so the lookup silently returned `None` — causing every valid subquery row-DQ rule to be incorrectly rejected with *"Subquery does not contain FROM"*.

Closes #8

### Changes

- **`spark_expectations/utils/validate_rules.py`**
  - Add `import sqlglot.expressions as sqlglot_expr`
  - Replace all `sqlglot.Expression` type annotations with `sqlglot_expr.Expression`
  - Replace `inner.args.get("from")` with `inner.find(sqlglot.expressions.From)` – a stable public API that works across all sqlglot versions

- **`pyproject.toml`**
  - Bump `sqlglot` upper bound from `<23.0` to `<31.0`

### Test Plan

- [x] All 166 unit tests in `tests/unit/utils/test_validate_rules.py` pass with **sqlglot 22.5.0** (old behaviour preserved)
- [x] All 166 unit tests pass with **sqlglot 30.2.1** (latest at time of fix)
- [x] All 44 unit tests in `tests/unit/rules/plugins/test_flatten.py` pass
- [x] Commit is GPG-signed

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by asingamaneni — COMMENTED** [review]
## Summary

This PR updates the sqlglot version constraint from `<23.0` to `<31.0` and modifies the `validate_rules.py` module to support both old and new sqlglot versions. The changes address a breaking API change in sqlglot 23.0 where the FROM clause was renamed internally from `from` to `from_`. The fix uses the stable `find()` public API instead of the internal `args.get("from")` method, plus adds an explicit import alias for `sqlglot.expressions`.

---

## Strengths

1. **Correct API Fix**: The migration from `inner.args.get("from")` to `inner.find(sqlglot.expressions.From)` is the right approach. The `find()` method is the stable public API that works across sqlglot versions, making this a future-proof solution.

2. **Clear Justification**: The inline comment explaining the change (lines 88-91) is excellent and will help maintainers understand why this pattern is needed.

3. **Backward Compatibility**: Using `find()` maintains compatibility with sqlglot <23.0, so the broadened version constraint is appropriate.

4. **Type Annotation Consistency**: Adding the explicit import `import sqlglot.expressions as sqlglot_expr` and using it throughout the type hints improves code clarity and consistency.

5. **Correct Null Check**: Changing the validation from `isinstance(from_node, ...)` to `if from_node is None` is correct, since `find()` returns `None` when no match is found.

6. **Minimal, Focused Changes**: The PR makes only the necessary changes without refactoring unrelated code.

---

## Concerns/Suggestions

1. **Incomplete Type Hint Migration**: While the PR updates type hints in method signatures (lines 108, 137, 161, 182), the implementation still uses `sqlglot.expressions.X` directly in several places:
   - Line 81: `isinstance(inner, sqlglot.expressions.Select)`
   - Line 94: `isinstance(source, (sqlglot.expressions.Table, sqlglot.expressions.Subquery, sqlglot.expressions.Join))`
   - Line 152, 154, 174, 177, 202, 234, 315: All still use `sqlglot.expressions.X`
   
   For consistency, consider applying the alias throughout the module (not just in type hints), or clarify the convention.

2. **Error Handling Edge Case**: Line 90 now checks `if from_node is None`, but consider whether the error message "[row_dq] Subquery does not contain FROM" is still appropriate. This check will still catch missing FROM clauses correctly, but it's worth confirming the behavior matches sqlglot's AST structure in all supported versions.

3. **Version Constraint Magnitude**: Jumping from `<23.0` to `<31.0` is a significant broadening. While the `find()` API is stable, consider:
   - Have you tested with sqlglot 30.x to confirm no other breaking changes exist?
   - The CLAUDE.md notes that sqlglot 23+ changed the AST API. Are there other changes in 24-30 that might affect this codebase?
   - A conservative approach might be to test with a few intermediate versions (e.g., 24.0, 25.0) before committing to `<31.0`.

4. **Test Coverage**: The PR diff doesn't show changes to test files. For sqlglot compatibility changes:
   - Are there existing tests that would catch this regression?
   - Consider adding a test that explicitly validates the `find()` pattern works correctly across versions.
   - Since the CLAUDE.md mentions this is a known issue, ensure the test suite validates both the old `args.get()` and new `find()` patterns (or at minimum documents the version requirement).

5. **Documentation**: The CLAUDE.md file in the project root mentions this issue as an open item ("There's an open PR (#9) to address this"). Once merged, that documentation should be updated to reflect resolution.

---

## Code Quality

- **Formatting**: Code adheres to Black formatting (120 char line length).
- **Import Organization**: The new import `import sqlglot.expressions as sqlglot_expr` is placed correctly after `import sqlglot`.
- **Error Messages**: Remain clear and diagnostic.

---

## Overall Assessment

**Recommendation: Approve with minor follow-up**

This is a solid, targeted fix that correctly addresses the sqlglot 23.0 API breakage. The use of `find()` is the right approach, and the version constraint broadening is reasonable given the API stability.

Before merge, I'd recommend:
1. Confirm test suite passes with at least sqlglot 24.x and 30.x (not just 21-22 and 23).
2. Apply the `sqlglot_expr` alias consistently throughout the module for cleaner code (optional but recommended).
3. Update CLAUDE.md to reflect this issue is resolved.

The changes are low-risk and should unblock users on newer sqlglot versions without breaking existing compatibility.

**Comment by asingamaneni** [comment]
Addressed review feedback:

- **Type alias consistency**: All  references now use the  alias consistently throughout validate_rules.py (function parameters, isinstance checks, find_all calls, etc.)

- **Inline documentation**: Added clear comment at line 88-89 explaining the sqlglot >=23 API change: 'args.get("from") no longer works. Use find(exp.From) which is stable across both old and new versions.'

- **Test coverage**: Verified that existing test suite (tests/unit/utils/test_validate_rules.py) already covers FROM clause detection through:
  - test_validate_single_subquery_invalid_from() - validates subqueries without FROM clause raise exceptions
  - Multiple parameterized test cases in VALIDATE_SUBQUERY_INVALID_FROM

- **Code formatting**: All changes formatted with Black (line-length=120)

**Comment by asingamaneni** [comment]
Merged into `dev` branch for consolidated upstream PR. See branch: https://github.com/asingamaneni/spark-expectations/tree/dev
